export default [
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/lokesh_coder/128.jpg',
    name: 'Chandler Jacobi',
    diagnosis: 'Depression',
    age: 25,
    status: 'primary',
    date: 'Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/suribbles/128.jpg',
    name: 'Monserrat Marquardt',
    diagnosis: 'Anxiety',
    age: 47,
    status: 'danger',
    date: 'Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jjsiii/128.jpg',
    name: 'Lonie Wyman',
    diagnosis: 'Anxiety',
    age: 25,
    status: 'success',
    date: 'Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/holdenweb/128.jpg',
    name: 'Corine Abernathy',
    diagnosis: 'ADHD',
    age: 12,
    status: 'warning',
    date: 'Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/operatino/128.jpg',
    name: 'Lorenz Botsford',
    diagnosis: 'Anxiety',
    age: 35,
    status: 'neutral',
    date: 'Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/akmur/128.jpg',
    name: 'Everette Botsford',
    diagnosis: 'ADHD',
    age: 12,
    status: 'success',
    date: 'Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/nateschulte/128.jpg',
    name: 'Marilou Beahan',
    diagnosis: 'Anxiety',
    age: 41,
    status: 'success',
    date: 'Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jerrybai1907/128.jpg',
    name: 'Ceasar Sauer',
    diagnosis: 'Anxiety',
    age: 48,
    status: 'primary',
    date: 'Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg',
    name: 'Rae McDermott',
    diagnosis: 'Anxiety',
    age: 50,
    status: 'danger',
    date: 'Sat Feb 01 2020 12:57:03 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/rtgibbons/128.jpg',
    name: 'Mable Steuber',
    diagnosis: 'Depression',
    age: 91,
    status: 'danger',
    date: 'Mon Sep 09 2019 12:03:25 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/danthms/128.jpg',
    name: 'Julian Glover',
    diagnosis: 'Anxiety',
    age: 65,
    status: 'danger',
    date: 'Fri May 22 2020 17:46:12 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/andysolomon/128.jpg',
    name: 'Duncan Toy',
    diagnosis: 'Anxiety',
    age: 12,
    status: 'danger',
    date: 'Sun Nov 17 2019 11:59:50 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/jesseddy/128.jpg',
    name: 'Blanche Friesen',
    diagnosis: 'Anxiety',
    age: 67,
    status: 'danger',
    date: 'Sun Jun 21 2020 16:46:39 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/haruintesettden/128.jpg',
    name: 'Orion Koepp',
    diagnosis: 'Anxiety',
    age: 44,
    status: 'danger',
    date: 'Thu Jun 04 2020 18:29:41 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/vocino/128.jpg',
    name: 'Dakota Vandervort',
    diagnosis: 'Depression',
    age: 76,
    status: 'danger',
    date: 'Fri Jan 31 2020 13:02:55 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/zaki3d/128.jpg',
    name: 'Lily Collier',
    diagnosis: 'Anxiety',
    age: 44,
    status: 'danger',
    date: 'Sun Aug 18 2019 14:52:01 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/evanshajed/128.jpg',
    name: 'Kayleigh Schumm',
    diagnosis: 'Depression',
    age: 65,
    status: 'danger',
    date: 'Wed May 06 2020 17:49:09 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/mdsisto/128.jpg',
    name: 'General McGlynn',
    diagnosis: 'ADHD',
    age: 30,
    status: 'danger',
    date: 'Mon Mar 30 2020 01:24:54 GMT-0300 (Brasilia Standard Time)',
  },
  {
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/woodydotmx/128.jpg',
    name: 'Shayna Schumm',
    diagnosis: 'Depression',
    age: 31,
    status: 'danger',
    date: 'Wed Jul 03 2019 10:01:06 GMT-0300 (Brasilia Standard Time)',
  }
];